from src.cleaning_segregation import clean_split_data
from src.feature_engineering import feature_engineering
from src.model_train_score import model_training
from src.model_train_score import model_scoring