NUMERICAL_VARS = ["pclass", "age", "sibsp", "parch", "fare"]
CATEGORICAL_VARS = ["sex", "cabin", "embarked", "title"]
TARGET = "survived"
RANDOM_SEED = 404
TRAIN_DATA_FILE = "data/cleaned/train.csv"
TEST_DATA_FILE = "data/cleaned/test.csv"
PROCESSED_TRAIN_DATA_FILE = "data/processed/train.csv"
PROCESSED_TEST_DATA_FILE = "data/processed/test.csv"
TRAIN_TARGET_FILE = "data/cleaned/y_train.csv"
TEST_TARGET_FILE = "data/cleaned/y_test.csv"
MODEL_FILE = "models/logistic_regression/log_reg.pkl"